<a href="https://colab.research.google.com/github/aanchan1/mongodb/blob/main/Mongodb_studentdatabase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install dnspython
!-m pip install pymongo[srv]

Requirement already satisfied: dnspython in /usr/local/lib/python3.7/dist-packages (2.2.1)
/bin/bash: - : invalid option
Usage:	/bin/bash [GNU long option] [option] ...
	/bin/bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--rcfile
	--restricted
	--verbose
	--version
Shell options:
	-ilrsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option

In [2]:
import pandas as pd
df=pd.read_json("students.json",lines=True)
df

     _id              name                                             scores
0      0        aimee Zank  [{'score': 1.463179736705023, 'type': 'exam'},...
1      1  Aurelia Menendez  [{'score': 60.06045071030959, 'type': 'exam'},...
2      2       Corliss Zuk  [{'score': 67.03077096065002, 'type': 'exam'},...
3      3        Bao Ziglar  [{'score': 71.64343899778332, 'type': 'exam'},...
4      4  Zachary Langlais  [{'score': 78.68385091304332, 'type': 'exam'},...
..   ...               ...                                                ...
195  195     Linnie Weigel  [{'score': 52.44578368517977, 'type': 'exam'},...
196  196  Santiago Dollins  [{'score': 52.04052571137036, 'type': 'exam'},...
197  197     Tonisha Games  [{'score': 38.51269589995049, 'type': 'exam'},...
198  198    Timothy Harrod  [{'score': 11.9075674046519, 'type': 'exam'}, ...
199  199        Rae Kohout  [{'score': 82.11742562118049, 'type': 'exam'},...

[200 rows x 3 columns]

In [3]:
df['scores'][0]

[{'score': 1.463179736705023, 'type': 'exam'},
 {'score': 11.78273309957772, 'type': 'quiz'},
 {'score': 35.8740349954354, 'type': 'homework'}]

In [4]:
df['scores'][0][0]["score"]

1.463179736705023

In [5]:
df['scores'][0][1]["score"]

11.78273309957772

In [6]:
df['scores'][0][2]["score"]

35.8740349954354

In [7]:
exam=[]
quiz=[]
homework=[]
for i in range(0,len(df)):
  exam.append(df['scores'][i][0]["score"])
  quiz.append(df['scores'][i][1]["score"])
  homework.append(df['scores'][i][2]["score"])
df['Exam']=exam
df['Quiz']=quiz
df['Homework']=homework
df

,_id,name,scores,Exam,Quiz,Homework
0,0,aimee Zank,"[{'score': 1.463179736705023, 'type': 'exam'},...",1.463180,11.782733,35.874035
1,1,Aurelia Menendez,"[{'score': 60.06045071030959, 'type': 'exam'},...",60.060451,52.797907,71.761334
2,2,Corliss Zuk,"[{'score': 67.03077096065002, 'type': 'exam'},...",67.030771,6.301852,66.283447
3,3,Bao Ziglar,"[{'score': 71.64343899778332, 'type': 'exam'},...",71.643439,24.802213,42.261471
4,4,Zachary Langlais,"[{'score': 78.68385091304332, 'type': 'exam'},...",78.683851,90.296310,34.416201
...,...,...,...,...,...,...
195,195,Linnie Weigel,"[{'score': 52.44578368517977, 'type': 'exam'},...",52.445784,90.777505,11.750084
196,196,Santiago Dollins,"[{'score': 52.04052571137036, 'type': 'exam'},...",52.040526,33.633001,78.792574
197,197,Tonisha Games,"[{'score': 38.51269589995049, 'type': 'exam'},...",38.512696,31.162876,79.158564
198,198,Timothy Harrod,"[{'score': 11.9075674046519, 'type': 'exam'}, ...",11.907567,20.518800,64.856504
199,199,Rae Kohout,"[{'score': 82.11742562118049, 'type': 'exam'},...",82.117426,49.612955,28.868237

In [8]:
df.drop(['scores'],axis=1,inplace=True)
df.drop(['_id'],axis=1,inplace=True)
df['Total']=df.iloc[:,1:4].sum(axis=1)
df['Percentage']=df.iloc[:,1:4].mean(axis=1)
df

                 name       Exam       Quiz   Homework       Total  Percentage
0          aimee Zank   1.463180  11.782733  35.874035   49.119948   16.373316
1    Aurelia Menendez  60.060451  52.797907  71.761334  184.619692   61.539897
2         Corliss Zuk  67.030771   6.301852  66.283447  139.616069   46.538690
3          Bao Ziglar  71.643439  24.802213  42.261471  138.707123   46.235708
4    Zachary Langlais  78.683851  90.296310  34.416201  203.396363   67.798788
..                ...        ...        ...        ...         ...         ...
195     Linnie Weigel  52.445784  90.777505  11.750084  154.973373   51.657791
196  Santiago Dollins  52.040526  33.633001  78.792574  164.466100   54.822033
197     Tonisha Games  38.512696  31.162876  79.158564  148.834135   49.611378
198    Timothy Harrod  11.907567  20.518800  64.856504   97.282871   32.427624
199        Rae Kohout  82.117426  49.612955  28.868237  160.598617   53.532872

[200 rows x 6 columns]

In [9]:
import pymongo
from pymongo import MongoClient
client = pymongo.MongoClient("mongodb+srv://datascience:jjjjaaaa@cluster0.nlhi0.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.test

In [10]:
db=client.get_database('studentdatabase')
records=db.studentdatabase
records.count_documents({})

0

In [11]:
for i in range(len(df)):
  a=df.iloc[i].to_dict()
  records.insert_one(a)

 1)Find the student name who scored maximum scores in all (exam, quiz and homework)?

In [12]:
highestmark=records.find().sort("Total",-1).limit(1)
for x in highestmark:
  print(x)

{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1a'), 'name': 'Jessika Dagenais', 'Exam': 90.47179954427436, 'Quiz': 90.3001402468489, 'Homework': 95.17753772405909, 'Total': 275.94947751518237, 'Percentage': 91.98315917172745}

2)      Find students who scored below average in the exam and pass mark is 40%?

In [13]:
belowaverage=records.find({"Exam": {"$gte":40, "$lte":50}})
for x in belowaverage:
  print(x)

{'_id': ObjectId('623dcb96b4d05f2bd8fdeb12'), 'name': 'Wilburn Spiess', 'Exam': 44.87186330181261, 'Quiz': 25.72395114668016, 'Homework': 63.42288310628662, 'Total': 134.0186975547794, 'Percentage': 44.67289918492647}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb17'), 'name': 'Denisha Cast', 'Exam': 45.61876862259409, 'Quiz': 98.35723209418343, 'Homework': 55.90835657173456, 'Total': 199.8843572885121, 'Percentage': 66.62811909617069}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb20'), 'name': 'Gisela Levin', 'Exam': 44.51211101958831, 'Quiz': 0.6578497966368001, 'Homework': 93.36341655949683, 'Total': 138.53337737572195, 'Percentage': 46.17779245857398}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb21'), 'name': 'Tressa Schwing', 'Exam': 42.17439799514388, 'Quiz': 71.99314840599558, 'Homework': 81.23972632069464, 'Total': 195.4072727218341, 'Percentage': 65.1357575739447}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb22'), 'name': 'Rosana Vales', 'Exam': 46.2289476258328, 'Quiz': 98.34164225207036, 'Homework': 36.18769746805938, 'Total': 180.75828734596254, 'Percentage': 60.25276244865418}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb24'), 'name': 'Tamika Schildgen', 'Exam': 45.65432764125526, 'Quiz': 64.32927049658846, 'Homework': 83.53933351660562, 'Total': 193.52293165444934, 'Percentage': 64.50764388481645}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2a'), 'name': 'Gwyneth Garling', 'Exam': 48.36644963899371, 'Quiz': 10.37827022865908, 'Homework': 93.26639335532833, 'Total': 152.01111322298112, 'Percentage': 50.67037107432704}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb37'), 'name': 'Kayce Kenyon', 'Exam': 44.62441703708117, 'Quiz': 27.38208798553111, 'Homework': 97.43587143437509, 'Total': 169.44237645698738, 'Percentage': 56.48079215232912}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3a'), 'name': 'Terica Brugger', 'Exam': 42.1011312120801, 'Quiz': 41.73654145887228, 'Homework': 18.91287189072117, 'Total': 102.75054456167354, 'Percentage': 34.250181520557845}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb46'), 'name': 'Chad Rahe', 'Exam': 40.84572027366789, 'Quiz': 29.22733629679561, 'Homework': 93.12112348179406, 'Total': 163.19418005225754, 'Percentage': 54.398060017419176}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb51'), 'name': 'Jenise Mcguffie', 'Exam': 40.15210496060384, 'Quiz': 90.60219950183566, 'Homework': 51.58720341010564, 'Total': 182.34150787254515, 'Percentage': 60.780502624181715}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb66'), 'name': 'Cassi Heal', 'Exam': 43.04310994985133, 'Quiz': 0.006247360551892, 'Homework': 63.88558436723092, 'Total': 106.93494167763413, 'Percentage': 35.644980559211376}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb71'), 'name': 'Demarcus Audette', 'Exam': 47.42608580155614, 'Quiz': 44.83416623719906, 'Homework': 39.01726616178844, 'Total': 131.27751820054362, 'Percentage': 43.75917273351454}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb73'), 'name': 'Mercedez Garduno', 'Exam': 49.52877007656483, 'Quiz': 44.55505066212384, 'Homework': 81.50869746632009, 'Total': 175.59251820500876, 'Percentage': 58.53083940166959}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7a'), 'name': 'Flora Duell', 'Exam': 40.68238966626067, 'Quiz': 46.77972040308903, 'Homework': 69.29400057020965, 'Total': 156.75611063955935, 'Percentage': 52.252036879853115}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8b'), 'name': 'Quincy Danaher', 'Exam': 40.53136904234401, 'Quiz': 83.09270171511093, 'Homework': 79.004550587978, 'Total': 202.62862134543295, 'Percentage': 67.54287378181098}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8d'), 'name': 'Alix Sherrill', 'Exam': 43.67436243299881, 'Quiz': 14.98112420690882, 'Homework': 23.62416821198536, 'Total': 82.279654851893, 'Percentage': 27.426551617297665}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9b'), 'name': 'Laureen Salomone', 'Exam': 42.54322973844196, 'Quiz': 33.03152379449381, 'Homework': 77.52357320933667, 'Total': 153.09832674227243, 'Percentage': 51.03277558075748}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9c'), 'name': 'Gwyneth Garling', 'Exam': 44.29553481758053, 'Quiz': 23.15599504527296, 'Homework': 84.83695219376807, 'Total': 152.28848205662155, 'Percentage': 50.76282735220718}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba8'), 'name': 'Aleida Elsass', 'Exam': 42.89558347656537, 'Quiz': 94.10647660402866, 'Homework': 30.56402201379193, 'Total': 167.56608209438596, 'Percentage': 55.855360698128656}
{'_id': ObjectId('623dcb9db4d05f2bd8fdebb1'), 'name': 'Alica Pasley', 'Exam': 41.3852820348269, 'Quiz': 87.0183839032626, 'Homework': 37.22917544696978, 'Total': 165.63284138505927, 'Percentage': 55.21094712835309}
{'_id': ObjectId('623dcb9db4d05f2bd8fdebb4'), 'name': 'Malisa Jeanes', 'Exam': 40.68676040665008, 'Quiz': 52.60826688242043, 'Homework': 94.67979508129564, 'Total': 187.97482237036616, 'Percentage': 62.658274123455385}
{'_id': ObjectId('623dcb9eb4d05f2bd8fdebc5'), 'name': 'Harriett Velarde', 'Exam': 41.47988283148075, 'Quiz': 95.69493673358075, 'Homework': 83.03916048182315, 'Total': 220.21398004688467, 'Percentage': 73.40466001562822}
{'_id': ObjectId('623dcb9eb4d05f2bd8fdebc6'), 'name': 'Kam Senters', 'Exam': 49.8822537074033, 'Quiz': 45.29515361387067, 'Homework': 68.88048980292801, 'Total': 164.057897124202, 'Percentage': 54.68596570806733}
{'_id': ObjectId('623dcb9fb4d05f2bd8fdebce'), 'name': 'Mariela Sherer', 'Exam': 47.67196715489599, 'Quiz': 41.55743490493954, 'Homework': 70.4612811769744, 'Total': 159.69068323680995, 'Percentage': 53.230227745603315}

3)      Find students who scored below pass mark and assigned them as fail, and above pass mark as pass in all the categories.

In [14]:
pass_fail_details=records.aggregate(
   [
      {
         "$project":
           {
             "name": True ,
             "Exam":
               {
                 "$cond": [ { "$gte": [ "$Exam", 40 ] }, "Pass", "Fail" ]
               },
            "Quiz":
               {
                 "$cond": [ { "$gte": [ "$Quiz", 40 ] }, "Pass", "Fail" ]
               },
            "Homework":
               {
                 "$cond": [ { "$gte": [ "$Homework", 40 ] }, "Pass", "Fail" ]
               }
           }
      }
   ]
)
for k in pass_fail_details:
  print(k)

{'_id': ObjectId('623dcb96b4d05f2bd8fdeb0d'), 'name': 'aimee Zank', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb0e'), 'name': 'Aurelia Menendez', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb0f'), 'name': 'Corliss Zuk', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb10'), 'name': 'Bao Ziglar', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb11'), 'name': 'Zachary Langlais', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb12'), 'name': 'Wilburn Spiess', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb13'), 'name': 'Jenette Flanders', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb14'), 'name': 'Salena Olmos', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb15'), 'name': 'Daphne Zheng', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb16'), 'name': 'Sanda Ryba', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb17'), 'name': 'Denisha Cast', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb18'), 'name': 'Marcus Blohm', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb19'), 'name': 'Quincy Danaher', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1a'), 'name': 'Jessika Dagenais', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1b'), 'name': 'Alix Sherrill', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1c'), 'name': 'Tambra Mercure', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1d'), 'name': 'Dodie Staller', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1e'), 'name': 'Fletcher Mcconnell', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb1f'), 'name': 'Verdell Sowinski', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb20'), 'name': 'Gisela Levin', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb21'), 'name': 'Tressa Schwing', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb22'), 'name': 'Rosana Vales', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb23'), 'name': 'Margart Vitello', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb24'), 'name': 'Tamika Schildgen', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb25'), 'name': 'Jesusa Rickenbacker', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb26'), 'name': 'Rudolph Domingo', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb27'), 'name': 'Jonie Raby', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb28'), 'name': 'Edgar Sarkis', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb29'), 'name': 'Laureen Salomone', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2a'), 'name': 'Gwyneth Garling', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2b'), 'name': 'Kaila Deibler', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2c'), 'name': 'Tandra Meadows', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2d'), 'name': 'Gwen Honig', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2e'), 'name': 'Sadie Jernigan', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2f'), 'name': 'Carli Belvins', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb30'), 'name': 'Synthia Labelle', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb31'), 'name': 'Eugene Magdaleno', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb32'), 'name': 'Meagan Oakes', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb33'), 'name': 'Richelle Siemers', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb34'), 'name': 'Mariette Batdorf', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb35'), 'name': 'Rachell Aman', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb36'), 'name': 'Aleida Elsass', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb37'), 'name': 'Kayce Kenyon', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb38'), 'name': 'Ernestine Macfarland', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb39'), 'name': 'Houston Valenti', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3a'), 'name': 'Terica Brugger', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3b'), 'name': 'Lady Lefevers', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3c'), 'name': 'Kurtis Jiles', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3d'), 'name': 'Barbera Lippman', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3e'), 'name': 'Dinah Sauve', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3f'), 'name': 'Alica Pasley', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb40'), 'name': 'Elizabet Kleine', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb41'), 'name': 'Tawana Oberg', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb42'), 'name': 'Malisa Jeanes', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb43'), 'name': 'Joel Rueter', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb44'), 'name': 'Tresa Sinha', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb45'), 'name': 'Danika Loeffler', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb46'), 'name': 'Chad Rahe', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb47'), 'name': 'Joaquina Arbuckle', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb48'), 'name': 'Vinnie Auerbach', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb49'), 'name': 'Dusti Lemmond', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4a'), 'name': 'Grady Zemke', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4b'), 'name': 'Vina Matsunaga', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4c'), 'name': 'Rubie Winton', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4d'), 'name': 'Whitley Fears', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4e'), 'name': 'Gena Riccio', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4f'), 'name': 'Kim Xu', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb50'), 'name': 'Merissa Mann', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb51'), 'name': 'Jenise Mcguffie', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb52'), 'name': 'Cody Strouth', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb53'), 'name': 'Harriett Velarde', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb54'), 'name': 'Kam Senters', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb55'), 'name': 'Leonida Lafond', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb56'), 'name': 'Devorah Smartt', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb57'), 'name': 'Leola Lundin', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb58'), 'name': 'Tonia Surace', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb59'), 'name': 'Adrien Renda', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5a'), 'name': 'Efrain Claw', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5b'), 'name': 'Len Treiber', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5c'), 'name': 'Mariela Sherer', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5d'), 'name': 'Echo Pippins', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5e'), 'name': 'Linnie Weigel', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb5f'), 'name': 'Santiago Dollins', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb60'), 'name': 'Tonisha Games', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb61'), 'name': 'Timothy Harrod', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb62'), 'name': 'Rae Kohout', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb63'), 'name': 'Brain Lachapelle', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb64'), 'name': 'Toshiko Sabella', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb65'), 'name': 'Keesha Papadopoulos', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb66'), 'name': 'Cassi Heal', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb67'), 'name': 'Osvaldo Hirt', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb68'), 'name': 'Ty Barbieri', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb69'), 'name': 'Ta Sikorski', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6a'), 'name': 'Lucinda Vanderburg', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6b'), 'name': 'Darby Wass', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6c'), 'name': 'Omar Bowdoin', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6d'), 'name': 'Milan Mcgavock', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6e'), 'name': 'Maren Scheider', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6f'), 'name': 'Carli Ector', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb70'), 'name': 'Jaclyn Morado', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb71'), 'name': 'Demarcus Audette', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb72'), 'name': 'Tania Hulett', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb73'), 'name': 'Mercedez Garduno', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb74'), 'name': 'Fleta Duplantis', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb75'), 'name': 'Brittny Warwick', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb76'), 'name': 'Shin Allbright', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb77'), 'name': 'Karry Petrarca', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb78'), 'name': 'Beckie Millington', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb79'), 'name': 'Mikaela Meidinger', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7a'), 'name': 'Flora Duell', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7b'), 'name': 'Nobuko Linzey', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7c'), 'name': 'Gennie Ratner', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7d'), 'name': 'Myrtle Wolfinger', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7e'), 'name': '', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7f'), 'name': 'aimee Zank', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb80'), 'name': 'Aurelia Menendez', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb81'), 'name': 'Corliss Zuk', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb82'), 'name': 'Bao Ziglar', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb83'), 'name': 'Zachary Langlais', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb84'), 'name': 'Wilburn Spiess', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb85'), 'name': 'Jenette Flanders', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb86'), 'name': 'Salena Olmos', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb87'), 'name': 'Daphne Zheng', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb88'), 'name': 'Sanda Ryba', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb89'), 'name': 'Denisha Cast', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb8a'), 'name': 'Marcus Blohm', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8b'), 'name': 'Quincy Danaher', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8c'), 'name': 'Jessika Dagenais', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8d'), 'name': 'Alix Sherrill', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8e'), 'name': 'Tambra Mercure', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8f'), 'name': 'Dodie Staller', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb90'), 'name': 'Fletcher Mcconnell', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb91'), 'name': 'Verdell Sowinski', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb92'), 'name': 'Gisela Levin', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb93'), 'name': 'Tressa Schwing', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb94'), 'name': 'Rosana Vales', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb95'), 'name': 'Margart Vitello', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb96'), 'name': 'Tamika Schildgen', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb97'), 'name': 'Jesusa Rickenbacker', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb98'), 'name': 'Rudolph Domingo', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb99'), 'name': 'Jonie Raby', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9a'), 'name': 'Edgar Sarkis', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9b'), 'name': 'Laureen Salomone', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9c'), 'name': 'Gwyneth Garling', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9d'), 'name': 'Kaila Deibler', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9e'), 'name': 'Tandra Meadows', 'Exam': 'Fail', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9f'), 'name': 'Gwen Honig', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba0'), 'name': 'Sadie Jernigan', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba1'), 'name': 'Carli Belvins', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba2'), 'name': 'Synthia Labelle', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba3'), 'name': 'Eugene Magdaleno', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba4'), 'name': 'Meagan Oakes', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba5'), 'name': 'Richelle Siemers', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba6'), 'name': 'Mariette Batdorf', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba7'), 'name': 'Rachell Aman', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba8'), 'name': 'Aleida Elsass', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Fail'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba9'), 'name': 'Kayce Kenyon', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdebaa'), 'name': 'Ernestine Macfarland', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdebab'), 'name': 'Houston Valenti', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdebac'), 'name': 'Terica Brugger', 'Exam': 'Pass', 'Quiz': 'Pass', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdebad'), 'name': 'Lady Lefevers', 'Exam': 'Pass', 'Quiz': 'Fail', 'Homework': 'Pass'}
{'_id': ObjectId('623dcb9db4d05f2bd8fdebae'), 'name': 'Kurtis Jiles', 'Exam': 'Fail', 'Quiz': 'Pass', 'Homework': 'Pass'}

4)       Find the total and average of the exam, quiz and homework and store them in a separate collection.

In [15]:
total_avg=records.aggregate(
   [
      {
         "$project":
           {
             "name": True ,
             'total' : { '$add' : [ '$Exam', '$Quiz',"$Homework" ]
              },
            'average': { '$avg' : [ '$Exam', '$Quiz',"$Homework" ]
              }
           }
      }
   ]
)
for k in total_avg:
  print(k)

{'_id': ObjectId('623dcb96b4d05f2bd8fdeb0d'), 'name': 'aimee Zank', 'total': 49.11994783171814, 'average': 16.373315943906046}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb0e'), 'name': 'Aurelia Menendez', 'total': 184.61969202100374, 'average': 61.53989734033458}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb0f'), 'name': 'Corliss Zuk', 'total': 139.61606947126907, 'average': 46.53868982375636}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb10'), 'name': 'Bao Ziglar', 'total': 138.70712252233457, 'average': 46.23570750744486}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb11'), 'name': 'Zachary Langlais', 'total': 203.3963625302728, 'average': 67.79878751009093}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb12'), 'name': 'Wilburn Spiess', 'total': 134.0186975547794, 'average': 44.67289918492647}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb13'), 'name': 'Jenette Flanders', 'total': 147.2203575476617, 'average': 49.07345251588723}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb14'), 'name': 'Salena Olmos', 'total': 229.3959334774732, 'average': 76.46531115915774}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb15'), 'name': 'Daphne Zheng', 'total': 112.71677331754347, 'average': 37.57225777251449}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb16'), 'name': 'Sanda Ryba', 'total': 220.08328118626565, 'average': 73.36109372875522}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb17'), 'name': 'Denisha Cast', 'total': 199.8843572885121, 'average': 66.62811909617069}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb18'), 'name': 'Marcus Blohm', 'total': 248.5091538691126, 'average': 82.83638462303753}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb19'), 'name': 'Quincy Danaher', 'total': 220.3184379933348, 'average': 73.4394793311116}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1a'), 'name': 'Jessika Dagenais', 'total': 275.94947751518237, 'average': 91.98315917172745}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1b'), 'name': 'Alix Sherrill', 'total': 118.48870352377075, 'average': 39.49623450792358}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1c'), 'name': 'Tambra Mercure', 'total': 117.50008641174173, 'average': 39.16669547058058}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1d'), 'name': 'Dodie Staller', 'total': 120.13675287379564, 'average': 40.045584291265214}
{'_id': ObjectId('623dcb96b4d05f2bd8fdeb1e'), 'name': 'Fletcher Mcconnell', 'total': 218.24398017942121, 'average': 72.7479933931404}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb1f'), 'name': 'Verdell Sowinski', 'total': 228.46404278930964, 'average': 76.15468092976988}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb20'), 'name': 'Gisela Levin', 'total': 138.53337737572195, 'average': 46.17779245857398}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb21'), 'name': 'Tressa Schwing', 'total': 195.4072727218341, 'average': 65.1357575739447}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb22'), 'name': 'Rosana Vales', 'total': 180.75828734596254, 'average': 60.25276244865418}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb23'), 'name': 'Margart Vitello', 'total': 182.00563535570944, 'average': 60.66854511856982}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb24'), 'name': 'Tamika Schildgen', 'total': 193.52293165444934, 'average': 64.50764388481645}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb25'), 'name': 'Jesusa Rickenbacker', 'total': 149.10807613148083, 'average': 49.70269204382694}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb26'), 'name': 'Rudolph Domingo', 'total': 148.54969223180623, 'average': 49.51656407726875}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb27'), 'name': 'Jonie Raby', 'total': 139.96370462720506, 'average': 46.65456820906835}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb28'), 'name': 'Edgar Sarkis', 'total': 82.6560500090462, 'average': 27.552016669682065}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb29'), 'name': 'Laureen Salomone', 'total': 93.67011710439672, 'average': 31.223372368132242}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2a'), 'name': 'Gwyneth Garling', 'total': 152.01111322298112, 'average': 50.67037107432704}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2b'), 'name': 'Kaila Deibler', 'total': 139.48229678140956, 'average': 46.49409892713652}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2c'), 'name': 'Tandra Meadows', 'total': 150.89635115040903, 'average': 50.29878371680301}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2d'), 'name': 'Gwen Honig', 'total': 263.26630272241187, 'average': 87.75543424080395}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2e'), 'name': 'Sadie Jernigan', 'total': 158.6873725512847, 'average': 52.895790850428234}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb2f'), 'name': 'Carli Belvins', 'total': 163.84548928047394, 'average': 54.61516309349131}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb30'), 'name': 'Synthia Labelle', 'total': 137.7409456810277, 'average': 45.91364856034257}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb31'), 'name': 'Eugene Magdaleno', 'total': 219.003552388691, 'average': 73.00118412956367}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb32'), 'name': 'Meagan Oakes', 'total': 193.9294745099881, 'average': 64.64315816999603}
{'_id': ObjectId('623dcb97b4d05f2bd8fdeb33'), 'name': 'Richelle Siemers', 'total': 182.2378812069286, 'average': 60.74596040230953}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb34'), 'name': 'Mariette Batdorf', 'total': 156.18768410864072, 'average': 52.062561369546906}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb35'), 'name': 'Rachell Aman', 'total': 180.20639736938892, 'average': 60.068799123129644}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb36'), 'name': 'Aleida Elsass', 'total': 191.3374155242169, 'average': 63.7791385080723}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb37'), 'name': 'Kayce Kenyon', 'total': 169.44237645698738, 'average': 56.48079215232912}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb38'), 'name': 'Ernestine Macfarland', 'total': 124.72878418014199, 'average': 41.57626139338066}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb39'), 'name': 'Houston Valenti', 'total': 114.15826509656077, 'average': 38.05275503218692}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3a'), 'name': 'Terica Brugger', 'total': 102.75054456167355, 'average': 34.25018152055785}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3b'), 'name': 'Lady Lefevers', 'total': 131.29270853967185, 'average': 43.76423617989062}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3c'), 'name': 'Kurtis Jiles', 'total': 147.7356498111623, 'average': 49.24521660372076}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3d'), 'name': 'Barbera Lippman', 'total': 206.96494520146337, 'average': 68.98831506715446}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3e'), 'name': 'Dinah Sauve', 'total': 183.2179783546083, 'average': 61.072659451536104}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb3f'), 'name': 'Alica Pasley', 'total': 168.7205264204154, 'average': 56.2401754734718}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb40'), 'name': 'Elizabet Kleine', 'total': 200.94891534204805, 'average': 66.98297178068269}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb41'), 'name': 'Tawana Oberg', 'total': 266.99578221547233, 'average': 88.99859407182412}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb42'), 'name': 'Malisa Jeanes', 'total': 121.1518349933377, 'average': 40.38394499777923}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb43'), 'name': 'Joel Rueter', 'total': 242.0364415445718, 'average': 80.6788138481906}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb44'), 'name': 'Tresa Sinha', 'total': 244.5023996395232, 'average': 81.50079987984107}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb45'), 'name': 'Danika Loeffler', 'total': 119.00689284424402, 'average': 39.668964281414674}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb46'), 'name': 'Chad Rahe', 'total': 163.19418005225754, 'average': 54.398060017419176}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb47'), 'name': 'Joaquina Arbuckle', 'total': 120.66923159080469, 'average': 40.223077196934895}
{'_id': ObjectId('623dcb98b4d05f2bd8fdeb48'), 'name': 'Vinnie Auerbach', 'total': 131.55784600976585, 'average': 43.85261533658862}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb49'), 'name': 'Dusti Lemmond', 'total': 182.36423465019507, 'average': 60.78807821673169}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4a'), 'name': 'Grady Zemke', 'total': 197.34049948667015, 'average': 65.78016649555671}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4b'), 'name': 'Vina Matsunaga', 'total': 132.2872844609489, 'average': 44.09576148698297}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4c'), 'name': 'Rubie Winton', 'total': 72.74345907466646, 'average': 24.247819691555488}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4d'), 'name': 'Whitley Fears', 'total': 268.6463713649928, 'average': 89.54879045499759}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4e'), 'name': 'Gena Riccio', 'total': 177.76002098364026, 'average': 59.25334032788009}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb4f'), 'name': 'Kim Xu', 'total': 94.82481083119796, 'average': 31.608270277065987}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb50'), 'name': 'Merissa Mann', 'total': 222.43538108594768, 'average': 74.14512702864923}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb51'), 'name': 'Jenise Mcguffie', 'total': 182.34150787254515, 'average': 60.780502624181715}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb52'), 'name': 'Cody Strouth', 'total': 202.4848718127078, 'average': 67.4949572709026}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb53'), 'name': 'Harriett Velarde', 'total': 176.07490979439646, 'average': 58.691636598132156}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb54'), 'name': 'Kam Senters', 'total': 178.913172052241, 'average': 59.63772401741367}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb55'), 'name': 'Leonida Lafond', 'total': 206.92216095602325, 'average': 68.97405365200775}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb56'), 'name': 'Devorah Smartt', 'total': 132.19316603930335, 'average': 44.06438867976778}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb57'), 'name': 'Leola Lundin', 'total': 216.63267038170724, 'average': 72.21089012723574}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb58'), 'name': 'Tonia Surace', 'total': 201.82584001807396, 'average': 67.27528000602466}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb59'), 'name': 'Adrien Renda', 'total': 147.47020593990004, 'average': 49.15673531330001}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5a'), 'name': 'Efrain Claw', 'total': 175.44760101431834, 'average': 58.48253367143945}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5b'), 'name': 'Len Treiber', 'total': 116.94520656066045, 'average': 38.98173552022015}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5c'), 'name': 'Mariela Sherer', 'total': 204.9282017860081, 'average': 68.30940059533603}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5d'), 'name': 'Echo Pippins', 'total': 205.47216171064758, 'average': 68.49072057021586}
{'_id': ObjectId('623dcb99b4d05f2bd8fdeb5e'), 'name': 'Linnie Weigel', 'total': 171.94196655853844, 'average': 57.313988852846144}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb5f'), 'name': 'Santiago Dollins', 'total': 181.00006173963334, 'average': 60.33335391321111}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb60'), 'name': 'Tonisha Games', 'total': 131.11934974450202, 'average': 43.706449914834}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb61'), 'name': 'Timothy Harrod', 'total': 216.29819060759476, 'average': 72.09939686919826}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb62'), 'name': 'Rae Kohout', 'total': 178.820098003648, 'average': 59.60669933454934}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb63'), 'name': 'Brain Lachapelle', 'total': 135.07862363042534, 'average': 45.02620787680845}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb64'), 'name': 'Toshiko Sabella', 'total': 90.29289206681383, 'average': 30.097630688937944}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb65'), 'name': 'Keesha Papadopoulos', 'total': 183.8870127743818, 'average': 61.29567092479393}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb66'), 'name': 'Cassi Heal', 'total': 106.93494167763413, 'average': 35.644980559211376}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb67'), 'name': 'Osvaldo Hirt', 'total': 185.53797432894692, 'average': 61.8459914429823}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb68'), 'name': 'Ty Barbieri', 'total': 206.94394766986875, 'average': 68.98131588995625}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb69'), 'name': 'Ta Sikorski', 'total': 115.74213180964733, 'average': 38.58071060321578}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6a'), 'name': 'Lucinda Vanderburg', 'total': 114.55089488600422, 'average': 38.183631628668074}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6b'), 'name': 'Darby Wass', 'total': 155.7771022790884, 'average': 51.925700759696134}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6c'), 'name': 'Omar Bowdoin', 'total': 122.70623232239147, 'average': 40.90207744079716}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6d'), 'name': 'Milan Mcgavock', 'total': 104.19377141035015, 'average': 34.731257136783384}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6e'), 'name': 'Maren Scheider', 'total': 231.17881123988664, 'average': 77.05960374662888}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb6f'), 'name': 'Carli Ector', 'total': 244.82763178118856, 'average': 81.60921059372951}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb70'), 'name': 'Jaclyn Morado', 'total': 174.5461576760983, 'average': 58.18205255869943}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb71'), 'name': 'Demarcus Audette', 'total': 131.27751820054362, 'average': 43.75917273351454}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb72'), 'name': 'Tania Hulett', 'total': 155.30833228670144, 'average': 51.769444095567145}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb73'), 'name': 'Mercedez Garduno', 'total': 175.59251820500876, 'average': 58.53083940166959}
{'_id': ObjectId('623dcb9ab4d05f2bd8fdeb74'), 'name': 'Fleta Duplantis', 'total': 178.1433701618344, 'average': 59.38112338727814}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb75'), 'name': 'Brittny Warwick', 'total': 247.51315928921287, 'average': 82.50438642973762}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb76'), 'name': 'Shin Allbright', 'total': 236.5473215674034, 'average': 78.84910718913447}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb77'), 'name': 'Karry Petrarca', 'total': 58.45858761680128, 'average': 19.486195872267093}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb78'), 'name': 'Beckie Millington', 'total': 129.29870077731468, 'average': 43.09956692577156}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb79'), 'name': 'Mikaela Meidinger', 'total': 211.94374606058196, 'average': 70.64791535352732}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7a'), 'name': 'Flora Duell', 'total': 156.75611063955935, 'average': 52.252036879853115}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7b'), 'name': 'Nobuko Linzey', 'total': 173.43955303906787, 'average': 57.81318434635596}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7c'), 'name': 'Gennie Ratner', 'total': 208.03498281392888, 'average': 69.34499427130963}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7d'), 'name': 'Myrtle Wolfinger', 'total': 203.79119045268433, 'average': 67.93039681756144}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7e'), 'name': '', 'total': 158.1297878869123, 'average': 52.70992929563744}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb7f'), 'name': 'aimee Zank', 'total': 130.9721943324432, 'average': 43.6573981108144}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb80'), 'name': 'Aurelia Menendez', 'total': 105.10579094395169, 'average': 35.035263647983896}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb81'), 'name': 'Corliss Zuk', 'total': 221.3468479915618, 'average': 73.78228266385393}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb82'), 'name': 'Bao Ziglar', 'total': 154.0475585018162, 'average': 51.34918616727207}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb83'), 'name': 'Zachary Langlais', 'total': 205.6587944217254, 'average': 68.55293147390846}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb84'), 'name': 'Wilburn Spiess', 'total': 210.29151529851958, 'average': 70.09717176617319}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb85'), 'name': 'Jenette Flanders', 'total': 107.87159055374062, 'average': 35.95719685124687}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb86'), 'name': 'Salena Olmos', 'total': 110.68556639219787, 'average': 36.89518879739929}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb87'), 'name': 'Daphne Zheng', 'total': 171.68464931123447, 'average': 57.22821643707815}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb88'), 'name': 'Sanda Ryba', 'total': 71.27146027282822, 'average': 23.757153424276073}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb89'), 'name': 'Denisha Cast', 'total': 118.2341215780863, 'average': 39.4113738593621}
{'_id': ObjectId('623dcb9bb4d05f2bd8fdeb8a'), 'name': 'Marcus Blohm', 'total': 137.0342890305606, 'average': 45.678096343520195}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8b'), 'name': 'Quincy Danaher', 'total': 202.62862134543295, 'average': 67.54287378181098}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8c'), 'name': 'Jessika Dagenais', 'total': 263.3989659226766, 'average': 87.79965530755887}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8d'), 'name': 'Alix Sherrill', 'total': 82.27965485189299, 'average': 27.426551617297662}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8e'), 'name': 'Tambra Mercure', 'total': 195.46779056021487, 'average': 65.15593018673829}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb8f'), 'name': 'Dodie Staller', 'total': 199.56471905226374, 'average': 66.52157301742125}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb90'), 'name': 'Fletcher Mcconnell', 'total': 149.26675330972444, 'average': 49.755584436574814}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb91'), 'name': 'Verdell Sowinski', 'total': 145.68727217339975, 'average': 48.562424057799916}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb92'), 'name': 'Gisela Levin', 'total': 123.94644554660488, 'average': 41.315481848868295}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb93'), 'name': 'Tressa Schwing', 'total': 166.0992291248508, 'average': 55.366409708283605}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb94'), 'name': 'Rosana Vales', 'total': 112.23313600351938, 'average': 37.41104533450646}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb95'), 'name': 'Margart Vitello', 'total': 166.81836101629523, 'average': 55.60612033876507}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb96'), 'name': 'Tamika Schildgen', 'total': 159.53213257952987, 'average': 53.17737752650996}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb97'), 'name': 'Jesusa Rickenbacker', 'total': 115.54875333859893, 'average': 38.51625111286631}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb98'), 'name': 'Rudolph Domingo', 'total': 160.0864123492324, 'average': 53.36213744974413}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb99'), 'name': 'Jonie Raby', 'total': 102.86145390316119, 'average': 34.28715130105373}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9a'), 'name': 'Edgar Sarkis', 'total': 199.81866315163785, 'average': 66.60622105054595}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9b'), 'name': 'Laureen Salomone', 'total': 153.09832674227243, 'average': 51.03277558075748}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9c'), 'name': 'Gwyneth Garling', 'total': 152.28848205662155, 'average': 50.76282735220718}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9d'), 'name': 'Kaila Deibler', 'total': 183.09592918689077, 'average': 61.03197639563026}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9e'), 'name': 'Tandra Meadows', 'total': 87.5629850401662, 'average': 29.1876616800554}
{'_id': ObjectId('623dcb9cb4d05f2bd8fdeb9f'), 'name': 'Gwen Honig', 'total': 201.4156031244819, 'average': 67.1385343748273}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba0'), 'name': 'Sadie Jernigan', 'total': 141.02791381651215, 'average': 47.00930460550405}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba1'), 'name': 'Carli Belvins', 'total': 174.61862132435388, 'average': 58.20620710811796}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba2'), 'name': 'Synthia Labelle', 'total': 141.50995457365985, 'average': 47.16998485788662}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba3'), 'name': 'Eugene Magdaleno', 'total': 126.52248166745107, 'average': 42.174160555817025}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba4'), 'name': 'Meagan Oakes', 'total': 186.33086651795293, 'average': 62.11028883931764}
{'_id': ObjectId('623dcb9db4d05f2bd8fdeba5'), 'name': 'Richelle Siemers', 'total': 139.60355242003698, 'average': 46.53451747334566}

5)      Create a new collection which consists of students who scored below average and above 40% in all the categories.

In [16]:
below_avg_above_pass=[]
for i in records.find({"$and":[{'Exam':{"$gte":40,"$lt":50}},{'Quiz':{"$gte":40,"$lt":50}},{'Homework':{"$gte":40,"$lt":50}}]}):
  below_avg_above_pass.append(i)
print(below_avg_above_pass)

[]

There are no records with students who scored below average(50) and above 40%

6)      Create a new collection which consists of students who scored below the fail mark in all the categories.

In [17]:
fail_mark=[]
for i in records.find({"$and":[{'Exam':{"$lt":40}},{'Quiz':{"$lt":40}},{'Homework':{"$lt":40}}]}):

  fail_mark.append(i)
fail_mark

[{'Exam': 1.463179736705023,
  'Homework': 35.8740349954354,
  'Percentage': 16.373315943906046,
  'Quiz': 11.78273309957772,
  'Total': 49.11994783171814,
  '_id': ObjectId('623dcb96b4d05f2bd8fdeb0d'),
  'name': 'aimee Zank'}]

7)      Create a new collection which consists of students who scored above pass mark in all the categories.

In [18]:
passed=[]

for i in records.find({"$and":[{'Exam':{"$gte":40}},{'Quiz':{"$gte":40}},{'Homework':{"$gte":40}}]}).sort('Percentage',-1):
  passed.append(i)
    
passed

[{'Exam': 90.47179954427436,
  'Homework': 95.17753772405909,
  'Percentage': 91.98315917172745,
  'Quiz': 90.3001402468489,
  'Total': 275.94947751518237,
  '_id': ObjectId('623dcb96b4d05f2bd8fdeb1a'),
  'name': 'Jessika Dagenais'},
 {'Exam': 89.61845831842888,
  'Homework': 96.57912148645883,
  'Percentage': 89.54879045499759,
  'Quiz': 82.44879156010508,
  'Total': 268.6463713649928,
  '_id': ObjectId('623dcb99b4d05f2bd8fdeb4d'),
  'name': 'Whitley Fears'},
 {'Exam': 80.59006098671075,
  'Homework': 93.12134003887978,
  'Percentage': 88.99859407182413,
  'Quiz': 93.28438118988183,
  'Total': 266.9957822154724,
  '_id': ObjectId('623dcb98b4d05f2bd8fdeb41'),
  'name': 'Tawana Oberg'},
 {'Exam': 96.93459855769822,
  'Homework': 70.7887302106597,
  'Percentage': 87.79965530755887,
  'Quiz': 95.6756371543187,
  'Total': 263.3989659226766,
  '_id': ObjectId('623dcb9cb4d05f2bd8fdeb8c'),
  'name': 'Jessika Dagenais'},
 {'Exam': 87.14345376886205,
  'Homework': 76.66460454219344,
  'Percentage': 87.75543424080395,
  'Quiz': 99.45824441135635,
  'Total': 263.26630272241187,
  '_id': ObjectId('623dcb97b4d05f2bd8fdeb2d'),
  'name': 'Gwen Honig'},
 {'Exam': 94.67153825229884,
  'Homework': 75.86075840047938,
  'Percentage': 84.27772532462807,
  'Quiz': 82.30087932110595,
  'Total': 252.83317597388418,
  '_id': ObjectId('623dcb9fb4d05f2bd8fdebcc'),
  'name': 'Efrain Claw'},
 {'Exam': 97.822030541043,
  'Homework': 62.01976292987356,
  'Percentage': 83.80153277618476,
  'Quiz': 91.56280485763772,
  'Total': 251.40459832855427,
  '_id': ObjectId('623dcb9db4d05f2bd8fdebac'),
  'name': 'Terica Brugger'},
 {'Exam': 78.42617835651868,
  'Homework': 87.49924733328717,
  'Percentage': 82.83638462303753,
  'Quiz': 82.58372817930675,
  'Total': 248.5091538691126,
  '_id': ObjectId('623dcb96b4d05f2bd8fdeb18'),
  'name': 'Marcus Blohm'},
 {'Exam': 69.54399888097534,
  'Homework': 95.96446106607902,
  'Percentage': 82.50438642973762,
  'Quiz': 82.00469934215849,
  'Total': 247.51315928921287,
  '_id': ObjectId('623dcb9bb4d05f2bd8fdeb75'),
  'name': 'Brittny Warwick'},
 {'Exam': 83.68438201130127,
  'Homework': 89.57200947426745,
  'Percentage': 82.35190304107267,
  'Quiz': 73.79931763764928,
  'Total': 247.055709123218,
  '_id': ObjectId('623dcb9eb4d05f2bd8fdebc3'),
  'name': 'Jenise Mcguffie'},
 {'Exam': 88.18040268522668,
  'Homework': 96.33612053785647,
  'Percentage': 81.60921059372951,
  'Quiz': 60.3111085581054,
  'Total': 244.82763178118853,
  '_id': ObjectId('623dcb9ab4d05f2bd8fdeb6f'),
  'name': 'Carli Ector'},
 {'Exam': 94.93136959210354,
  'Homework': 77.248768811767,
  'Percentage': 81.50079987984105,
  'Quiz': 72.32226123565266,
  'Total': 244.50239963952316,
  '_id': ObjectId('623dcb98b4d05f2bd8fdeb44'),
  'name': 'Tresa Sinha'},
 {'Exam': 79.24755285478162,
  'Homework': 67.0528222080174,
  'Percentage': 81.19388235379569,
  'Quiz': 97.28127199858804,
  'Total': 243.58164706138706,
  '_id': ObjectId('623dcb9db4d05f2bd8fdebb3'),
  'name': 'Tawana Oberg'},
 {'Exam': 87.53636893952853,
  'Homework': 61.79032586247813,
  'Percentage': 80.6788138481906,
  'Quiz': 92.70974674256513,
  'Total': 242.0364415445718,
  '_id': ObjectId('623dcb98b4d05f2bd8fdeb43'),
  'name': 'Joel Rueter'},
 {'Exam': 62.28388941877533,
  'Homework': 88.9947941542333,
  'Percentage': 78.84910718913447,
  'Quiz': 85.26863799439475,
  'Total': 236.5473215674034,
  '_id': ObjectId('623dcb9bb4d05f2bd8fdeb76'),
  'name': 'Shin Allbright'},
 {'Exam': 94.4329121733663,
  'Homework': 59.46326216544371,
  'Percentage': 77.0596037466289,
  'Quiz': 77.28263690107663,
  'Total': 231.17881123988667,
  '_id': ObjectId('623dcb9ab4d05f2bd8fdeb6e'),
  'name': 'Maren Scheider'},
 {'Exam': 90.37826509157176,
  'Homework': 96.52986171633331,
  'Percentage': 76.46531115915774,
  'Quiz': 42.48780666956811,
  'Total': 229.3959334774732,
  '_id': ObjectId('623dcb96b4d05f2bd8fdeb14'),
  'name': 'Salena Olmos'},
 {'Exam': 62.12870233109035,
  'Homework': 81.58947824932574,
  'Percentage': 76.15468092976988,
  'Quiz': 84.74586220889356,
  'Total': 228.46404278930964,
  '_id': ObjectId('623dcb97b4d05f2bd8fdeb1f'),
  'name': 'Verdell Sowinski'},
 {'Exam': 64.16109192679477,
  'Homework': 96.0560340227047,
  'Percentage': 75.71814398628493,
  'Quiz': 66.93730600935531,
  'Total': 227.1544319588548,
  '_id': ObjectId('623dcb9fb4d05f2bd8fdebcb'),
  'name': 'Adrien Renda'},
 {'Exam': 75.1949733626123,
  'Homework': 94.67518167209815,
  'Percentage': 74.14512702864923,
  'Quiz': 52.56522605123723,
  'Total': 222.43538108594768,
  '_id': ObjectId('623dcb99b4d05f2bd8fdeb50'),
  'name': 'Merissa Mann'},
 {'Exam': 76.45468797439878,
  'Homework': 91.86573111689813,
  'Percentage': 73.78228266385393,
  'Quiz': 53.02642890026489,
  'Total': 221.3468479915618,
  '_id': ObjectId('623dcb9bb4d05f2bd8fdeb81'),
  'name': 'Corliss Zuk'},
 {'Exam': 54.29841278520669,
  'Homework': 80.40732356118075,
  'Percentage': 73.43947933111161,
  'Quiz': 85.61270164694737,
  'Total': 220.31843799333484,
  '_id': ObjectId('623dcb96b4d05f2bd8fdeb19'),
  'name': 'Quincy Danaher'},
 {'Exam': 41.47988283148075,
  'Homework': 83.03916048182315,
  'Percentage': 73.40466001562822,
  'Quiz': 95.69493673358075,
  'Total': 220.21398004688467,
  '_id': ObjectId('623dcb9eb4d05f2bd8fdebc5'),
  'name': 'Harriett Velarde'},
 {'Exam': 73.055900093666,
  'Homework': 66.09143669040472,
  'Percentage': 73.00118412956365,
  'Quiz': 79.85621560462026,
  'Total': 219.00355238869096,
  '_id': ObjectId('623dcb97b4d05f2bd8fdeb31'),
  'name': 'Eugene Magdaleno'},
 {'Exam': 93.23020013495737,
  'Homework': 74.00788699415295,
  'Percentage': 72.09939686919826,
  'Quiz': 49.06010347848443,
  'Total': 216.29819060759476,
  '_id': ObjectId('623dcb9ab4d05f2bd8fdeb61'),
  'name': 'Timothy Harrod'},
 {'Exam': 63.75595052560389,
  'Homework': 88.66481441499843,
  'Percentage': 70.64791535352732,
  'Quiz': 59.52298111997963,
  'Total': 211.94374606058196,
  '_id': ObjectId('623dcb9bb4d05f2bd8fdeb79'),
  'name': 'Mikaela Meidinger'},
 {'Exam': 52.36963021569788,
  'Homework': 61.35034001494281,
  'Percentage': 70.0971717661732,
  'Quiz': 96.5715450678789,
  'Total': 210.2915152985196,
  '_id': ObjectId('623dcb9bb4d05f2bd8fdeb84'),
  'name': 'Wilburn Spiess'},
 {'Exam': 62.74309964110307,
  'Homework': 53.11174468047395,
  'Percentage': 69.34499427130963,
  'Quiz': 92.18013849235186,
  'Total': 208.03498281392888,
  '_id': ObjectId('623dcb9bb4d05f2bd8fdeb7c'),
  'name': 'Gennie Ratner'},
 {'Exam': 62.20457822364115,
  'Homework': 82.41688205392703,
  'Percentage': 68.55293147390846,
  'Quiz': 61.03733414415722,
  'Total': 205.6587944217254,
  '_id': ObjectId('623dcb9bb4d05f2bd8fdeb83'),
  'name': 'Zachary Langlais'},
 {'Exam': 61.20158144877323,
  'Homework': 90.97004773806381,
  'Percentage': 68.30940059533603,
  'Quiz': 52.75657259917104,
  'Total': 204.9282017860081,
  '_id': ObjectId('623dcb99b4d05f2bd8fdeb5c'),
  'name': 'Mariela Sherer'},
 {'Exam': 52.22632020277269,
  'Homework': 86.80410157346574,
  'Percentage': 68.23914423017285,
  'Quiz': 65.68701091428014,
  'Total': 204.71743269051856,
  '_id': ObjectId('623dcb9eb4d05f2bd8fdebb6'),
  'name': 'Tresa Sinha'},
 {'Exam': 40.53136904234401,
  'Homework': 79.004550587978,
  'Percentage': 67.54287378181098,
  'Quiz': 83.09270171511093,
  'Total': 202.62862134543295,
  '_id': ObjectId('623dcb9cb4d05f2bd8fdeb8b'),
  'name': 'Quincy Danaher'},
 {'Exam': 80.93655069496523,
  'Homework': 41.34308724166419,
  'Percentage': 67.27528000602466,
  'Quiz': 79.54620208144452,
  'Total': 201.82584001807396,
  '_id': ObjectId('623dcb99b4d05f2bd8fdeb58'),
  'name': 'Tonia Surace'},
 {'Exam': 45.61876862259409,
  'Homework': 55.90835657173456,
  'Percentage': 66.62811909617069,
  'Quiz': 98.35723209418343,
  'Total': 199.8843572885121,
  '_id': ObjectId('623dcb96b4d05f2bd8fdeb17'),
  'name': 'Denisha Cast'},
 {'Exam': 65.99888014434269,
  'Homework': 75.06379354463246,
  'Percentage': 66.60622105054595,
  'Quiz': 58.75598946266268,
  'Total': 199.81866315163785,
  '_id': ObjectId('623dcb9cb4d05f2bd8fdeb9a'),
  'name': 'Edgar Sarkis'},
 {'Exam': 52.16051124848157,
  'Homework': 63.88857636557489,
  'Percentage': 66.52157301742125,
  'Quiz': 83.51563143820728,
  'Total': 199.56471905226374,
  '_id': ObjectId('623dcb9cb4d05f2bd8fdeb8f'),
  'name': 'Dodie Staller'},
 {'Exam': 51.91561300267121,
  'Homework': 95.34139273570386,
  'Percentage': 65.78016649555671,
  'Quiz': 50.08349374829509,
  'Total': 197.34049948667015,
  '_id': ObjectId('623dcb99b4d05f2bd8fdeb4a'),
  'name': 'Grady Zemke'},
 {'Exam': 62.61423873241083,
  'Homework': 85.20578508528978,
  'Percentage': 65.15593018673827,
  'Quiz': 47.64776674251425,
  'Total': 195.46779056021484,
  '_id': ObjectId('623dcb9cb4d05f2bd8fdeb8e'),
  'name': 'Tambra Mercure'},
 {'Exam': 42.17439799514388,
  'Homework': 81.23972632069464,
  'Percentage': 65.1357575739447,
  'Quiz': 71.99314840599558,
  'Total': 195.4072727218341,
  '_id': ObjectId('623dcb97b4d05f2bd8fdeb21'),
  'name': 'Tressa Schwing'},
 {'Exam': 45.65432764125526,
  'Homework': 83.53933351660562,
  'Percentage': 64.50764388481645,
  'Quiz': 64.32927049658846,
  'Total': 193.52293165444934,
  '_id': ObjectId('623dcb97b4d05f2bd8fdeb24'),
  'name': 'Tamika Schildgen'},
 {'Exam': 91.51968055194875,
  'Homework': 51.53939113583016,
  'Percentage': 64.47863279245041,
  'Quiz': 50.37682668957234,
  'Total': 193.43589837735124,
  '_id': ObjectId('623dcb9eb4d05f2bd8fdebbb'),
  'name': 'Dusti Lemmond'},
 {'Exam': 40.68676040665008,
  'Homework': 94.67979508129564,
  'Percentage': 62.658274123455385,
  'Quiz': 52.60826688242043,
  'Total': 187.97482237036616,
  '_id': ObjectId('623dcb9db4d05f2bd8fdebb4'),
  'name': 'Malisa Jeanes'},
 {'Exam': 67.44931456608883,
  'Homework': 76.30879472084027,
  'Percentage': 61.8459914429823,
  'Quiz': 41.77986504201782,
  'Total': 185.53797432894692,
  '_id': ObjectId('623dcb9ab4d05f2bd8fdeb67'),
  'name': 'Osvaldo Hirt'},
 {'Exam': 60.06045071030959,
  'Homework': 71.76133439165544,
  'Percentage': 61.53989734033458,
  'Quiz': 52.79790691903873,
  'Total': 184.61969202100374,
  '_id': ObjectId('623dcb96b4d05f2bd8fdeb0e'),
  'name': 'Aurelia Menendez'},
 {'Exam': 40.15210496060384,
  'Homework': 51.58720341010564,
  'Percentage': 60.780502624181715,
  'Quiz': 90.60219950183566,
  'Total': 182.34150787254515,
  '_id': ObjectId('623dcb99b4d05f2bd8fdeb51'),
  'name': 'Jenise Mcguffie'},
 {'Exam': 63.86894250781692,
  'Homework': 59.13566011309437,
  'Percentage': 59.60669933454934,
  'Quiz': 55.81549538273672,
  'Total': 178.820098003648,
  '_id': ObjectId('623dcb9ab4d05f2bd8fdeb62'),
  'name': 'Rae Kohout'},
 {'Exam': 67.58395308948619,
  'Homework': 42.93471779899529,
  'Percentage': 59.25334032788009,
  'Quiz': 67.2413500951588,
  'Total': 177.76002098364026,
  '_id': ObjectId('623dcb99b4d05f2bd8fdeb4e'),
  'name': 'Gena Riccio'},
 {'Exam': 60.314725741828,
  'Homework': 74.8699176311771,
  'Percentage': 58.76930603039721,
  'Quiz': 41.12327471818652,
  'Total': 176.30791809119162,
  '_id': ObjectId('623dcb9fb4d05f2bd8fdebc9'),
  'name': 'Leola Lundin'},
 {'Exam': 49.52877007656483,
  'Homework': 81.50869746632009,
  'Percentage': 58.53083940166959,
  'Quiz': 44.55505066212384,
  'Total': 175.59251820500876,
  '_id': ObjectId('623dcb9ab4d05f2bd8fdeb73'),
  'name': 'Mercedez Garduno'},
 {'Exam': 70.27627082122453,
  'Homework': 47.48518298423097,
  'Percentage': 58.18205255869943,
  'Quiz': 56.78470387064279,
  'Total': 174.5461576760983,
  '_id': ObjectId('623dcb9ab4d05f2bd8fdeb70'),
  'name': 'Jaclyn Morado'},
 {'Exam': 67.40792606687442,
  'Homework': 47.44831568815929,
  'Percentage': 57.81318434635596,
  'Quiz': 58.58331128403415,
  'Total': 173.43955303906787,
  '_id': ObjectId('623dcb9bb4d05f2bd8fdeb7b'),
  'name': 'Nobuko Linzey'},
 {'Exam': 49.8822537074033,
  'Homework': 68.88048980292801,
  'Percentage': 54.68596570806733,
  'Quiz': 45.29515361387067,
  'Total': 164.057897124202,
  '_id': ObjectId('623dcb9eb4d05f2bd8fdebc6'),
  'name': 'Kam Senters'},
 {'Exam': 47.67196715489599,
  'Homework': 70.4612811769744,
  'Percentage': 53.230227745603315,
  'Quiz': 41.55743490493954,
  'Total': 159.69068323680995,
  '_id': ObjectId('623dcb9fb4d05f2bd8fdebce'),
  'name': 'Mariela Sherer'},
 {'Exam': 40.68238966626067,
  'Homework': 69.29400057020965,
  'Percentage': 52.252036879853115,
  'Quiz': 46.77972040308903,
  'Total': 156.75611063955935,
  '_id': ObjectId('623dcb9bb4d05f2bd8fdeb7a'),
  'name': 'Flora Duell'}]